### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by siljeangelvik** [siljeangelvik/portfolio2-presentation#1]
- [x] Make **Contact** Drawer width smaller for responsiveness on mobile versions.

- [x] Add **Contact** component to **NavBar** component 

- [x] Add logo to **NavBar** component and **index.html** fav icon 

- [ ] Figure out what content to put in **About** component

- [x] Change Route or Link from '/*' to '/'

- [ ] Add Validation to the Contact Form and set it up to work with Netlify

- [ ] Add property "defaultChecked" to the **ThemeButton** component, try to make the button bigger.

- [ ] Set up custom theme with AntDesign ConfigProvider so the colours are not default

- [ ] Add **Footer** component (?)
